### ISSUE TITLE
rename repo name

### ISSUE THREAD

**Issue by radmanplays** [catfoolyou/Eaglercraft-1.12-Desktop-Runtime#10]
if you dont plan to port this to web you should rename the repo. "eaglercraft" is minecraft ported to web and eaglercraft runtime is just minecraft java that can join eaglercraft servers. having the name "Eaglercraft-1.12" for this repo makes it confusing bc this is NOT eaglercraft 1.12

**Comment by catfoolyou** [comment]
So maybe Eaglercraft 1.12 desktop runtime?

**Comment by radmanplays** [comment]
can it join eaglercraft servers?

**Comment by catfoolyou** [comment]
Yes, it can. Both 1.5.2 and 1.8 servers work. Read the README.
