### ISSUE TITLE
Eagler Authsystem GUI

### ISSUE THREAD

**Issue by catfoolyou** [catfoolyou/Eaglercraft-1.12-Desktop-Runtime#8]
Will need code from `GuiScreenEditProfile.java` and `GuiAuthenticationScreen.java` for the auth screen and setting the username
Probably will need everything under "profile"

Necessary changes:
- Reimplement skin setting
- Using minecraft's internal methods and keep usage of eaglercraftX stuff to a minimum
- Maybe use aperson's code instead if it works with stock unmodified 1.12.

**Comment by catfoolyou** [comment]
Use code from EaglercraftX's modified classes for rendering in `SkinPreviewRenderer` to bypass the crash on startup

```java
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelPlayer;
import net.minecraft.client.model.ModelZombie;
```

**Comment by thatdudejr** [comment]
why didn't you release it after you added the authentication?

**Comment by catfoolyou** [comment]
Wdym? I'm currently working on adding the skin system, but auth works in the latest stable release. Check that commit that's mentioned in the releases and download the source from there if you wanna work with it.
